### ISSUE TITLE
编译安装后播放视频异常

### ISSUE THREAD

**Issue by EGQM** [nekomiyaxneko/flutter_MyBilibili#14]
在ubuntu下，使用dart2.7.2+flutter 1.12.13_hotfix8-stable编译MyBilibili，可以编译通过（由部分警告，说API过期）。安装后，点击视频的时候，视频长时间不播放，卡在“正在获取弹幕”的地方。

**Comment by EGQM** [comment]
等很长的时候后，视频还是会播放。再接下载作者编译好的app，安装后，没有这个问题。

**Comment by nekomiyaxneko** [comment]
因为在flutter上直接获取弹幕数据会乱码，我就做了个中转服务器来解码，后来服务器过期了。我编译的应该是老版本，弹幕功能没有完善。

**Comment by EGQM** [comment]
如何在代码中暂时关掉弹幕呢？

**Comment by nekomiyaxneko** [comment]
可以尝试注释掉 `pages/home/video_play_page_with_danmaku.dart`中第135行的`await getDanmaku();`

**Comment by EGQM** [comment]
这个有问题，我之前试验了。这样的话，播放视频会异常。我现在是在getDanmaku函数中，把第一行改为：var data;即可。
