### ISSUE TITLE
视频详情新api,可以获取到粉丝数

### ISSUE THREAD

**Issue by dfaofeng** [nekomiyaxneko/flutter_MyBilibili#2]
"https://app.bilibili.com/x/v2/view?aid=57789195&appkey=1d8b6e7d45233436&build=5480400&ts=1570894094&sign=f152b3700bcf10f485e5f9d2711d0001"
sign算法为
aid=57789195&appkey=1d8b6e7d45233436&build=5480400&ts=1570894094560c52ccd288fed045859ed18bffd973
就是所有参数+560c52ccd288fed045859ed18bffd973

**Comment by nekomiyaxneko** [comment]
> "https://app.bilibili.com/x/v2/view?aid=57789195&appkey=1d8b6e7d45233436&build=5480400&ts=1570894094&sign=f152b3700bcf10f485e5f9d2711d0001"
> sign算法为
> aid=57789195&appkey=1d8b6e7d45233436&build=5480400&ts=1570894094560c52ccd288fed045859ed18bffd973
> 就是所有参数+560c52ccd288fed045859ed18bffd973

好的，谢谢你

**Comment by dfaofeng** [comment]
还有你那个获取视频链接的api也错误了.需要获取cid,index里面也有,自己可以修复下

**Comment by nekomiyaxneko** [comment]
视频链接的api是可以通过aid来获取播放链接的，用page参数来控制分p。
但是最近这个api使用不了。

**Comment by dfaofeng** [comment]
> 视频链接的api是可以通过aid来获取播放链接的，用page参数来控制分p。
> 但是最近这个api使用不了。

那就先获取cid,再用"https://api.bilibili.com/x/player/playurl?cid=123746967&avid=71417523&qn=112" 这个就可以获取到 视频地址了

**Comment by nekomiyaxneko** [comment]
我尝试了一下，获取到的视频url无法直接访问。
不过如果在请求url的headers加一个“Referer”:"https://api.bilibili.com/x/web-interface/view?aid=71417523", 就可以正常请求了。
但是有一个问题，flutter的videoplayer似乎不能设置request的headers。

**Comment by dfaofeng** [comment]
"https://github.com/CaiJingLong/flutter_ijkplayer”  这个项目了解下

**Comment by nekomiyaxneko** [comment]
这个我关注过，我最早是打算用这个的，但是有点不稳定，就放弃了。
刚刚用了它的example试了一下，加了headers也播放不了，出现HTTP error 459。
请问您有没有试过用这个插件（flutter_ijkplayer）来播放获取的视频地址？

**Comment by dfaofeng** [comment]
😂那 没得办法了？我去那个项目提issue看下有没有解决办法

**Comment by nekomiyaxneko** [comment]
我刚刚更新了一下，换了个api，现在可以播放了。
不过有个问题是不能快进，一拖动进度条就跳到开头。

**Comment by dfaofeng** [comment]
"https://fijkplayer.befovy.com/docs/zh/index.html" 我又找到这个项目😌

**Comment by dfaofeng** [comment]
晚上我试验下用客户端加密的api获取到视频流需不需要要加头部播放

**Comment by Xbs233** [comment]
获取视频播放地址时，一般`appKey`会换成` iVGUTjsxvpLeuDCf`
然后签名校验也变了，sign = 参数排字典序拼接上`aHRmhWMLkdeMuILqORnYZocwMBpMEOdt`再做一次md5
视频播放时没问题的 设置好Header 
Header:`Accept:*/*`
就是新视频都是音视频分离的m4s得自己做音画同步

**Comment by nekomiyaxneko** [comment]
好的谢谢。
不过除了ijkplayer以外，我还不知道flutter有什么视频播放器可以设置headers。

**Comment by dfaofeng** [comment]
> 获取视频播放地址时，一般`appKey`会换成` iVGUTjsxvpLeuDCf`
> 然后签名校验也变了，sign = 参数排字典序拼接上`aHRmhWMLkdeMuILqORnYZocwMBpMEOdt`再做一次md5
> 视频播放时没问题的 设置好Header
> Header:`Accept:*/*`
> 就是新视频都是音视频分离的m4s得自己做音画同步

我用最新版的客户端抓包获取获取视频url地址的api为"https://app.bilibili.com/x/playurl?device=android&expire=0&force_host=0&mobi_app=android&mid=0&appkey=iVGUTjsxvpLeuDCf&fnval=16&qn=32&actionkey=appkey&cid=103331583&from_spmid=tm.recommend.0.0&otype=json&fourk=0&platform=android&ts=1571496018783&build=5490400&fnver=0&buvid=XZF9F55FE566C57599024A397F5F160E74DBE&aid=59294027&spmid=main.ugc-video-detail.0.0&sign=035d22c7df1fb66e338a30e487593279"  用那个算法算到最后的sign值不对啊

**Comment by nekomiyaxneko** [comment]
> > 获取视频播放地址时，一般`appKey`会换成` iVGUTjsxvpLeuDCf`
> > 然后签名校验也变了，sign = 参数排字典序拼接上`aHRmhWMLkdeMuILqORnYZocwMBpMEOdt`再做一次md5
> > 视频播放时没问题的 设置好Header
> > Header:`Accept:*/*`
> > 就是新视频都是音视频分离的m4s得自己做音画同步
> 
> 我用最新版的客户端抓包获取获取视频url地址的api为"https://app.bilibili.com/x/playurl?device=android&expire=0&force_host=0&mobi_app=android&mid=0&appkey=iVGUTjsxvpLeuDCf&fnval=16&qn=32&actionkey=appkey&cid=103331583&from_spmid=tm.recommend.0.0&otype=json&fourk=0&platform=android&ts=1571496018783&build=5490400&fnver=0&buvid=XZF9F55FE566C57599024A397F5F160E74DBE&aid=59294027&spmid=main.ugc-video-detail.0.0&sign=035d22c7df1fb66e338a30e487593279" 用那个算法算到最后的sign值不对啊

这个你要先给参数按照key排序，再计算。
上面那个排完序应该是`actionkey=appkey&aid=59294027&appkey=iVGUTjsxvpLeuDCf&build=5490400&buvid=XZF9F55FE566C57599024A397F5F160E74DBE&cid=103331583&device=android&expire=0&fnval=16&fnver=0&force_host=0&fourk=0&from_spmid=tm.recommend.0.0&mid=0&mobi_app=android&otype=json&platform=android&qn=32&spmid=main.ugc-video-detail.0.0&ts=1571496018783`
再拼接上appsecret
md5加密后得sign=`035d22c7df1fb66e338a30e487593279`
我没用最新版接口是因为我不知道怎么合并视频和音频或者说怎么同步。
