### ISSUE TITLE
The current Dart SDK version is 2.4.0. 但是我用dart --version 查看是2.5.2了

### ISSUE THREAD

**Issue by cxd1314** [nekomiyaxneko/flutter_MyBilibili#3]
flutter packages get
Running "flutter pub get" in flutter_MyBilibili-master...       
The current Dart SDK version is 2.4.0.

Because flutter_MyBilibili depends on dio >=3.0.0-dev.1 which requires SDK version >2.4.0 <3.0.0, version solving failed.
pub get failed (1)
exit code 1

我用dart --version 查看是2.5.2了
到底为什么还出这个错？
我用mac Vscode 运行在iphone模拟器上的

**Comment by dfaofeng** [comment]
要求是flutter sdk版本吧 你flutter --version看看版本多少

**Comment by nekomiyaxneko** [comment]
你好，我没有遇到过这样的问题。
你可以尝试升级flutter的版本到最新版。

**Comment by cxd1314** [comment]
刚才的问题解决了 ,我用的是flutter 安装包下面的dart-sdk 2.4.0版本的， 但是命令行检测到的是usr目录下面的一个sdk 2.5.2版本

**Comment by cxd1314** [comment]
Because every version of flutter_test from sdk depends on path 1.6.2 and dio >=3.0.0-dev.1 depends on path ^1.6.4, flutter_test from sdk is incompatible with dio >=3.0.0-dev.1.

So, because flutter_MyBilibili depends on both dio ^3.0.2 and flutter_test any from sdk, version solving failed.
pub get failed (1)
exit code 1
又报错了
不知什么问题

**Comment by nekomiyaxneko** [comment]
您可以更新flutter到最新版本试试看。

**Comment by cxd1314** [comment]
升级到1.9.1了，The method 'MouseRegion' isn't defined for the class '_ChewieCustomWithDanmakuState'. 但是这个东西还是找不到

**Comment by nekomiyaxneko** [comment]
你尝试一下flutter packages get。
可以把报错信息尽量发全一点给我，谢谢。

**Comment by nekomiyaxneko** [comment]
另外可以尝试重启一下你的ide

**Comment by cxd1314** [comment]
重启之后 packages get 后
[flutter_MyBilibili-master] flutter packages get
Running "flutter pub get" in flutter_MyBilibili-master...           1.0s
exit code 0

**Comment by cxd1314** [comment]
这是vscode OUTPUT里面报的

**Comment by nekomiyaxneko** [comment]
您尝试运行一下，看看还有什么问题

**Comment by cxd1314** [comment]
重启后错误的problems消失了
但是运行到iphone模拟器有问题
    #import <image_gallery_saver/image_gallery_saver-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build descriptionwarning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.1.99. (in target 'FMDB' from project 'Pods')
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)

**Comment by nekomiyaxneko** [comment]
您可以看一下关于image_gallery_saver里关于IOS的  https://pub.dev/packages/image_gallery_saver
IOS方面我没接触不太了解

**Comment by cxd1314** [comment]
#import <image_gallery_saver/image_gallery_saver-Swift.h> 这个问题解决方法：
进入flutter_project/ios/,编辑Podfile，将
# platform :ios, '9.0'
替换为：

platform :ios, '10.0'
use_frameworks!

iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.1.99.
这个问题解决方法
在podfile的末尾加上
if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
这段代码 变成
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end
最终可以运行了!好感动！>_<

**Comment by nekomiyaxneko** [comment]
好的，感谢您提出的问题以及解决方法。
如果您对我的项目感兴趣的话，我们可以一起讨论。
我的邮箱：bill_lll@qq.com
