### ISSUE TITLE
弹幕播放有时候概率出现问题

### ISSUE THREAD

**Issue by dfaofeng** [nekomiyaxneko/flutter_MyBilibili#5]
![Screenshot_2019-10-20-22-13-43-565_com flutter bilibili](https://user-images.githubusercontent.com/14891398/67160842-71fc3780-f387-11e9-8801-5b78b3034d71.png)
概率出现这个问题...不知道是不是xml解析问题

**Comment by nekomiyaxneko** [comment]
已经修复了
